export const category = [
  { nameJa: "色", nameEn: "color", group: "noun" },
  { nameJa: "乗り物", nameEn: "vehicle", group: "noun" },
  { nameJa: "数字", nameEn: "number", group: "noun" },
  { nameJa: "スポーツ", nameEn: "sport", group: "verb" },
  { nameJa: "料理", nameEn: "cooking", group: "verb" },
  { nameJa: "性格", nameEn: "personality", group: "adj" },
  { nameJa: "気候", nameEn: "climate", group: "adj" },
  { nameJa: "気分", nameEn: "feeling", group: "adj" },
  { nameJa: "職業", nameEn: "occupation", group: "noun" },
  { nameJa: "家族", nameEn: "family", group: "noun" },
  { nameJa: "動物", nameEn: "animal", group: "noun" },
  { nameJa: "JLPT N5・N4", nameEn: "N5N4", group: "verb" },
];

export const data = {
  color: [
    { en: "blue", ja: "青", jaHiragana: "あお" },
    { en: "red", ja: "赤", jaHiragana: "あか" },
    { en: "yellow", ja: "黄色", jaHiragana: "きいろ" },
    { en: "purple", ja: "紫", jaHiragana: "むらさき" },
    { en: "orange", ja: "オレンジ", jaHiragana: "おれんじ" },
    { en: "brown", ja: "茶色", jaHiragana: "ちゃいろ" },
    { en: "white", ja: "白", jaHiragana: "しろ" },
    { en: "grey", ja: "灰色", jaHiragana: "はいいろ" },
    { en: "black", ja: "黒", jaHiragana: "くろ" },
    { en: "pink", ja: "ピンク", jaHiragana: "ぴんく" },
  ],
  vehicle: [
    { en: "car", ja: "車", jaHiragana: "くるま" },
    { en: "bus", ja: "バス", jaHiragana: "ばす" },
    { en: "bicycle", ja: "自転車", jaHiragana: "じてんしゃ" },
    { en: "taxi", ja: "タクシー", jaHiragana: "たくしー" },
    { en: "motorcycle", ja: "バイク", jaHiragana: "ばいく" },
    { en: "ambulance", ja: "救急車", jaHiragana: "きゅうきゅうしゃ" },
    { en: "truck", ja: "トラック", jaHiragana: "とらっく" },
    { en: "plane", ja: "飛行機", jaHiragana: "ひこうき" },
    { en: "ship", ja: "船", jaHiragana: "ふね" },
    { en: "train", ja: "電車", jaHiragana: "でんしゃ" },
  ],
  occupation: [
    { en: "driver", ja: "運転手", jaHiragana: "うんてんしゅ" },
    { en: "police officer", ja: "警察官", jaHiragana: "けいさつかん" },
    { en: "photographer", ja: "カメラマン", jaHiragana: "かめらまん" },
    { en: "nurse", ja: "看護士", jaHiragana: "かんごし" },
    { en: "doctor", ja: "医者", jaHiragana: "いしゃ" },
    { en: "engineer", ja: "エンジニア", jaHiragana: "えんじにあ" },
    { en: "teacher", ja: "教師", jaHiragana: "きょうし" },
    { en: "scientist", ja: "科学者", jaHiragana: "かがくしゃ" },
    { en: "bank staff", ja: "銀行員	", jaHiragana: "ぎんこういん" },
    { en: "singer", ja: "歌手", jaHiragana: "かしゅ" },
  ],
  family: [
    { en: "father", ja: "父", jaHiragana: "ちち" },
    { en: "mother", ja: "母", jaHiragana: "はは" },
    { en: "photographer", ja: "カメラマン", jaHiragana: "かめらまん" },
    { en: "older brother", ja: "兄", jaHiragana: "あに" },
    { en: "older sister", ja: "姉", jaHiragana: "あね" },
    { en: "younger brother", ja: "弟", jaHiragana: "おとうと" },
    { en: "younger sister", ja: "妹", jaHiragana: "いもうと" },
    { en: "grandfather", ja: "祖父", jaHiragana: "そふ" },
    { en: "grandmother", ja: "祖母	", jaHiragana: "そぼ" },
    { en: "grandchild", ja: "孫", jaHiragana: "まご" },
  ],
  animal: [
    { en: "dog", ja: "犬", jaHiragana: "いぬ" },
    { en: "cat", ja: "猫", jaHiragana: "ねこ" },
    { en: "bird", ja: "鳥", jaHiragana: "とり" },
    { en: "horse", ja: "馬", jaHiragana: "うま" },
    { en: "elephant", ja: "象", jaHiragana: "ぞう" },
    { en: "chicken", ja: "鶏", jaHiragana: "にわとり" },
    { en: "sheep", ja: "羊", jaHiragana: "ひつじ" },
    { en: "mouse", ja: "鼠", jaHiragana: "ねずみ" },
    { en: "monkey", ja: "猿", jaHiragana: "さる" },
    { en: "deer", ja: "鹿", jaHiragana: "しか" },
  ],
  sport: [
    { en: "to kick", ja: "蹴る", jaHiragana: "ける" },
    { en: "to catch (a ball)", ja: "捕る", jaHiragana: "とる" },
    { en: "to hit (a ball)", ja: "打つ", jaHiragana: "うつ" },
    { en: "to walk", ja: "歩く", jaHiragana: "あるく" },
    { en: "to run", ja: "走る", jaHiragana: "はしる" },
    { en: "to jump", ja: "跳ぶ", jaHiragana: "とぶ" },
    { en: "to do exercises", ja: "運動する", jaHiragana: "うんどうする" },
    { en: "to win", ja: "勝つ", jaHiragana: "かつ" },
    { en: "to lose", ja: "負ける", jaHiragana: "まける" },
    { en: "to climb", ja: "登る", jaHiragana: "のぼる" },
  ],
  cooking: [
    { en: "to grill", ja: "焼く", jaHiragana: "やく" },
    { en: "to boil", ja: "茹でる", jaHiragana: "ゆでる" },
    { en: "to fly", ja: "揚げる", jaHiragana: "あげる" },
    { en: "to wash (dishes)", ja: "洗う", jaHiragana: "あらう" },
    { en: "to dish up", ja: "盛り付ける", jaHiragana: "もりつける" },
    { en: "to stir-fry", ja: "炒める", jaHiragana: "いためる" },
    { en: "to steam", ja: "蒸す", jaHiragana: "むす" },
    { en: "to chop", ja: "刻む", jaHiragana: "きざむ" },
    { en: "to simmer", ja: "煮る", jaHiragana: "にる" },
    { en: "to mix", ja: "混ぜる", jaHiragana: "まぜる" },
  ],
  N5N4: [
    { en: "to go", ja: "行く", jaHiragana: "いく" },
    { en: "to return", ja: "帰る", jaHiragana: "かえる" },
    { en: "to drink", ja: "飲む", jaHiragana: "のむ" },
    { en: "to write", ja: "書く", jaHiragana: "かく" },
    { en: "to speak", ja: "話す", jaHiragana: "はなす" },
    { en: "to say", ja: "言う", jaHiragana: "いう" },
    { en: "to read", ja: "読む", jaHiragana: "よむ" },
    { en: "to meet", ja: "会う", jaHiragana: "あう" },
    { en: "to wait", ja: "待つ", jaHiragana: "まつ" },
    { en: "to understand", ja: "分かる", jaHiragana: "わかる" },
  ],
  personality: [
    { en: "quiet", ja: "大人しい", jaHiragana: "おとなしい" },
    { en: "mature", ja: "大人っぽい", jaHiragana: "おとなっぽい" },
    { en: "stubborn", ja: "頑固な", jaHiragana: "がんこな" },
    { en: "strict", ja: "厳しい", jaHiragana: "きびしい" },
    { en: "stingy", ja: "けちな", jaHiragana: "" },
    { en: "individualistic", ja: "個性的な", jaHiragana: "こせいてきな" },
    { en: "childish", ja: "子供っぽい", jaHiragana: "こどもっぽい" },
    { en: "hotnest", ja: "正直な", jaHiragana: "しょうじきな" },
    { en: "kind", ja: "親切な", jaHiragana: "しんせつな" },
    { en: "patient", ja: "忍耐強い", jaHiragana: "にんたいづよい" },
  ],
  climate: [
    { en: "warm", ja: "暖かい", jaHiragana: "あたたかい" },
    { en: "hot", ja: "暑い", jaHiragana: "あつい" },
    { en: "windy", ja: "風が強い", jaHiragana: "かぜがつよい" },
    { en: "dry", ja: "乾燥した", jaHiragana: "かんそうした" },
    { en: "cloudy", ja: "雲の多い", jaHiragana: "くものおおい" },
    { en: "cold", ja: "寒い", jaHiragana: "さむい" },
    { en: "cool", ja: "涼しい", jaHiragana: "すずしい" },
    { en: "chilly", ja: "肌寒い", jaHiragana: "はだざむい" },
    { en: "sunny", ja: "晴れている", jaHiragana: "はれている" },
    { en: "damp", ja: "ジメジメした", jaHiragana: "じめじめした" },
  ],
  feeling: [
    { en: "happy", ja: "幸せな", jaHiragana: "しあわせな" },
    { en: "sad", ja: "悲しい", jaHiragana: "かなしい" },
    { en: "glad", ja: "嬉しい", jaHiragana: "うれしい" },
    { en: "mad", ja: "怒っている", jaHiragana: "おこっている" },
    { en: "proud", ja: "誇りに思う", jaHiragana: "ほこりにおもう" },
    { en: "hurt", ja: "痛い", jaHiragana: "いたい" },
    { en: "nervous", ja: "緊張している", jaHiragana: "きんちょうしている" },
    { en: "lonely", ja: "寂しい", jaHiragana: "さみしい" },
    { en: "noisy", ja: "うるさい", jaHiragana: "" },
    { en: "sleepy", ja: "眠い", jaHiragana: "ねむい" },
  ],
};
